config/routes.rb
Rails.application.routes.draw do
  resources :roles
  resources :posts
  resources :permissions
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'posts#index', as: :authenticated_root
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root "posts#index"

end

app/models/permission.rb
# == Schema Information
#
# Table name: permissions
#
#  id         :bigint           not null, primary key
#  name       :string
#  action     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Permission < ApplicationRecord

  DEFAULT_CATEGORY = %w[Create Read Update Delete Show].freeze

  has_many :accesses, dependent: :destroy
  # has_many :roles, through: :accesses

  validates :name, presence: true, uniqueness: { scope: :action, case_sensitive: false }

  normalizes :action, with: ->(value) { value.strip.titleize }

  after_create :create_accesses

  private

  def create_accesses
    Role.find_each do |role|
      Access.create(role:, permission: self)
    end
  end
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  before_action :set_permission, only: %i[ show edit update destroy ]

  # GET /permissions or /permissions.json
  def index
    @permissions = Permission.all
  end

  # GET /permissions/1 or /permissions/1.json
  def show
  end

  # GET /permissions/new
  def new
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit
  end

  # Permission /permissions or /permissions.json
  def create
    @permission = Permission.new(permission_params)
    respond_to do |format|
      if @permission.save
        format.html { redirect_to permission_url(@permission), notice: "permission was successfully created." }
        format.json { render :show, status: :created, location: @permission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permissions/1 or /permissions/1.json
  def update
    authorize @permission
    respond_to do |format|
      if @permission.update(permission_params)
        format.html { redirect_to permission_url(@permission), notice: "permission was successfully updated." }
        format.json { render :show, status: :ok, location: @permission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1 or /permissions/1.json
  def destroy
    @permission.destroy!

    respond_to do |format|
      format.html { redirect_to permissions_url, notice: "permission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission
      @permission = Permission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def permission_params
      params.require(:permission).permit(:name, :action)
    end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/permissions/_form.html.erb
<%= form_with(model: permission) do |form| %>
  <% if permission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

      <ul>
        <% permission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :action, style: "display: block" %>
    <%= form.text_field :action %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/permissions/_permission.html.erb
<div id="<%= dom_id permission %>">
  <p>
    <strong>Name:</strong>
    <%= permission.name %>
  </p>

  <p>
    <strong>Action:</strong>
    <%= permission.action %>
  </p>

</div>

app/views/permissions/edit.html.erb
<h1>Editing permission</h1>

<%= render "form", permission: @permission %>

<br>

<div>
  <%= link_to "Show this permission", @permission %> |
  <%= link_to "Back to permissions", permissions_path %>
</div>

app/views/permissions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>permissions</h1>

<div id="permissions">
  <% @permissions.each do |permission| %>
    <%= render permission %>
    <p>
      <%= link_to "Show this permission", permission %>
    </p>
  <% end %>
</div>

<%= link_to "New permission", new_permission_path %>
<br>
<%= link_to "Roles", roles_path %>
<br>
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>

app/views/permissions/new.html.erb
<h1>New permission</h1>

<%= render "form", permission: @permission %>

<br>

<div>
  <%= link_to "Back to permissions", permissions_path %>
</div>

app/views/permissions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @permission %>

<div>
  <%= link_to "Edit this permission", edit_permission_path(@permission) %> |
  <%= link_to "Back to permissions", permissions_path %>

  <%= button_to "Destroy this permission", @permission, method: :delete %>
</div>